options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      pip install functions-framework
      gcloud builds submit --tag gcr.io/$PROJECT_ID/paperform-seminar-transformer .

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    [
      'gcloud', 'run', 'deploy', 'paperform-seminar-transformer',
      '--image', 'gcr.io/$PROJECT_ID/paperform-seminar-transformer',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
