options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Build & deploy directly using Google Cloud's gcloud CLI with buildpacks
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    [
      'run', 'deploy', 'paperform-seminar-transformer',
      '--source', '.',
      '--entry-point', 'process_pubsub_push',
      '--runtime', 'python311',
      '--region', 'us-central1',
      '--project', 'avian-cosmos-458703-g3',
      '--allow-unauthenticated'
    ]
